name: Filtrage Calendrier ICS

on:
  schedule:
    - cron: '0 * * * *' # Exécution automatique toutes les heures
  workflow_dispatch: # Te permet de déclencher le script manuellement depuis GitHub pour tester

jobs:
  update-ics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Droit strict pour pouvoir pusher le fichier généré
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Anticipation de la dépréciation Node 20

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Exécution du filtrage
        run: python filter_ics.py

      - name: Commit et Push (si modification)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add edt_propre.ics
          # Le diff vérifie s'il y a eu des changements dans l'ICS. Si oui, commit. Sinon, passe à la suite sans erreur.
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update : Synchronisation de l'emploi du temps"
          git push
